/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilaDinamica;
import javax.swing.JOptionPane;
import modelo.Persona;

/**
 *
 * @author christianecg
 */
public class VistaPilaD extends javax.swing.JFrame {
    private PilaD pila;
    private Persona nueva=new Persona();
    
    /**
     * Creates new form VistaPilaE
     */
    public VistaPilaD() {
        initComponents();
        this.pila=new PilaD();
    }

    /**evt
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_Dia = new javax.swing.JTextField();
        txf_Nombre = new javax.swing.JTextField();
        txf_Anio = new javax.swing.JTextField();
        txf_Mes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_Prueba = new javax.swing.JTextArea();
        btn_Push = new javax.swing.JButton();
        btn_Pop = new javax.swing.JButton();
        btn_Print = new javax.swing.JButton();
        btn_Tope = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Fecha de nacimiento:");

        txf_Dia.setBackground(new java.awt.Color(173, 194, 254));
        txf_Dia.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Dia.setForeground(new java.awt.Color(1, 1, 1));

        txf_Nombre.setBackground(new java.awt.Color(173, 194, 254));
        txf_Nombre.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Nombre.setForeground(new java.awt.Color(1, 1, 1));

        txf_Anio.setBackground(new java.awt.Color(173, 194, 254));
        txf_Anio.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Anio.setForeground(new java.awt.Color(1, 1, 1));

        txf_Mes.setBackground(new java.awt.Color(173, 194, 254));
        txf_Mes.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Mes.setForeground(new java.awt.Color(1, 1, 1));

        txa_Prueba.setColumns(20);
        txa_Prueba.setForeground(new java.awt.Color(1, 1, 1));
        txa_Prueba.setRows(5);
        jScrollPane1.setViewportView(txa_Prueba);

        btn_Push.setBackground(new java.awt.Color(46, 46, 46));
        btn_Push.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Push.setForeground(new java.awt.Color(254, 254, 254));
        btn_Push.setText("Push");
        btn_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PushActionPerformed(evt);
            }
        });

        btn_Pop.setBackground(new java.awt.Color(46, 46, 46));
        btn_Pop.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Pop.setForeground(new java.awt.Color(254, 254, 254));
        btn_Pop.setText("Pop");
        btn_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PopActionPerformed(evt);
            }
        });

        btn_Print.setBackground(new java.awt.Color(46, 46, 46));
        btn_Print.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Print.setForeground(new java.awt.Color(254, 254, 254));
        btn_Print.setText("Print");
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });

        btn_Tope.setBackground(new java.awt.Color(46, 46, 46));
        btn_Tope.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Tope.setForeground(new java.awt.Color(254, 254, 254));
        btn_Tope.setText("Tope");
        btn_Tope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TopeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txf_Nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Tope, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Push, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Pop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Pop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Push, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Tope, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PushActionPerformed
        try {
            nueva.setNombre(this.txf_Nombre.getText());
            nueva.setDd(this.validacionByte(this.txf_Dia.getText()));
            nueva.setMm(this.validacionByte(this.txf_Mes.getText()));
            nueva.setYyyy(this.validacionInt(this.txf_Anio.getText()));
            pila.push((Persona) nueva);
            txa_Prueba.setText(txa_Prueba.getText()+"Correctamente guardado\n");
            this.limpiar();
            btn_PrintActionPerformed(evt);
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage());
        }
    }//GEN-LAST:event_btn_PushActionPerformed

    private void btn_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PopActionPerformed
        try {
            pila.pop();
            txa_Prueba.setText(txa_Prueba.getText()+"Correctamente realizado\n");
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage());
        }
    }//GEN-LAST:event_btn_PopActionPerformed

    private void btn_TopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TopeActionPerformed
        try {
            txa_Prueba.setText(txa_Prueba.getText()+this.pila.getTope()+"\n");
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage());
        }
    }//GEN-LAST:event_btn_TopeActionPerformed

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        try {
            txa_Prueba.setText(txa_Prueba.getText()+this.pila.toString());
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage());
        }
    }//GEN-LAST:event_btn_PrintActionPerformed

    private int validacionInt(String x){
        try{
            return Integer.parseInt(x);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,x+" no es un valor entero. Rectifica");
        }
        return 0;
    }
    
    private byte validacionByte(String x){
        try{
            return Byte.parseByte(x);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,x+" no es un valor entero. Rectifica");
        }
        return 0;
    }
    
    private void limpiar(){
        this.txf_Nombre.setText("");
        this.txf_Dia.setText("");
        this.txf_Mes.setText("");
        this.txf_Anio.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPilaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPilaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPilaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPilaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPilaD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pop;
    private javax.swing.JButton btn_Print;
    private javax.swing.JButton btn_Push;
    private javax.swing.JButton btn_Tope;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_Prueba;
    private javax.swing.JTextField txf_Anio;
    private javax.swing.JTextField txf_Dia;
    private javax.swing.JTextField txf_Mes;
    private javax.swing.JTextField txf_Nombre;
    // End of variables declaration//GEN-END:variables
}
