package colaEstatica;
import javax.swing.JOptionPane;
import modelo.Persona;

/**
 *
 * @author christianecg
 */
public class VistaColaE extends javax.swing.JFrame {
    private ColaE cola;
    private Persona nueva;
    
    /**
     * Creates new form VistaPilaE
     */
    public VistaColaE() {
        initComponents();
        int t=0;
        do{
            t=this.validacionInt(JOptionPane.showInputDialog(this,"Ingrese el tamaño de la cola"));
        }while(t==0);
        this.cola=new ColaE(t);
    }

    /**evt
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_Dia = new javax.swing.JTextField();
        txf_Nombre = new javax.swing.JTextField();
        txf_Anio = new javax.swing.JTextField();
        txf_Mes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_Prueba = new javax.swing.JTextArea();
        btn_Insertar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Fecha de nacimiento:");

        txf_Dia.setBackground(new java.awt.Color(173, 194, 254));
        txf_Dia.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Dia.setForeground(new java.awt.Color(1, 1, 1));

        txf_Nombre.setBackground(new java.awt.Color(173, 194, 254));
        txf_Nombre.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Nombre.setForeground(new java.awt.Color(1, 1, 1));

        txf_Anio.setBackground(new java.awt.Color(173, 194, 254));
        txf_Anio.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Anio.setForeground(new java.awt.Color(1, 1, 1));

        txf_Mes.setBackground(new java.awt.Color(173, 194, 254));
        txf_Mes.setFont(new java.awt.Font("Cousine", 0, 12)); // NOI18N
        txf_Mes.setForeground(new java.awt.Color(1, 1, 1));

        txa_Prueba.setColumns(20);
        txa_Prueba.setForeground(new java.awt.Color(1, 1, 1));
        txa_Prueba.setRows(5);
        jScrollPane1.setViewportView(txa_Prueba);

        btn_Insertar.setBackground(new java.awt.Color(46, 46, 46));
        btn_Insertar.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Insertar.setForeground(new java.awt.Color(254, 254, 254));
        btn_Insertar.setText("Insertar");
        btn_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertarActionPerformed(evt);
            }
        });

        btn_Eliminar.setBackground(new java.awt.Color(46, 46, 46));
        btn_Eliminar.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(254, 254, 254));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Print.setBackground(new java.awt.Color(46, 46, 46));
        btn_Print.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        btn_Print.setForeground(new java.awt.Color(254, 254, 254));
        btn_Print.setText("Print");
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txf_Nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertarActionPerformed
        try {
            this.nueva=new Persona();
            nueva.setNombre(this.txf_Nombre.getText());
            nueva.setDd(this.validacionByte(this.txf_Dia.getText()));
            nueva.setMm(this.validacionByte(this.txf_Mes.getText()));
            nueva.setYyyy(this.validacionInt(this.txf_Anio.getText()));
            cola.insertar((Object) nueva);
            txa_Prueba.setText(txa_Prueba.getText()+"Correctamente guardado\n");
            this.limpiar();
            btn_PrintActionPerformed(evt);
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+" "+ex.getMessage()+"\n");
            System.err.println(ex);
        }
    }//GEN-LAST:event_btn_InsertarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        try {
            cola.eliminar();
            txa_Prueba.setText(txa_Prueba.getText()+"Correctamente realizado\n");
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage()+"\n");
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        try {
            txa_Prueba.setText(txa_Prueba.getText()+this.cola.print()+"\n");
        } catch (Exception ex) {
            txa_Prueba.setText(txa_Prueba.getText()+ex.getMessage()+"\n");
        }
    }//GEN-LAST:event_btn_PrintActionPerformed

    private int validacionInt(String x){
        try{
            return Integer.parseInt(x);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,x+" no es un valor entero. Rectifica");
        }
        return 0;
    }
    
    private byte validacionByte(String x){
        try{
            return Byte.parseByte(x);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,x+" no es un valor entero. Rectifica");
        }
        return 0;
    }
    
    private void limpiar(){
        this.txf_Nombre.setText("");
        this.txf_Dia.setText("");
        this.txf_Mes.setText("");
        this.txf_Anio.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaColaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaColaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaColaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaColaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaColaE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Insertar;
    private javax.swing.JButton btn_Print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_Prueba;
    private javax.swing.JTextField txf_Anio;
    private javax.swing.JTextField txf_Dia;
    private javax.swing.JTextField txf_Mes;
    private javax.swing.JTextField txf_Nombre;
    // End of variables declaration//GEN-END:variables
}
